logging:
  level:
    org.flywaydb: DEBUG
spring:
  application.name: springboot-app
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    enabled: true
    baseline-on-migrate: true
    schemas: public
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/flight_tracker
    username: postgres
    password: password
